# Generated by Django 5.2.8 on 2025-12-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="payment_date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="payment_method",
            new_name="method",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_amount",
        ),
        migrations.AddField(
            model_name="payment",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Укажите сумму платежа",
                null=True,
                verbose_name="Сумма платежа",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите id на сессии",
                max_length=255,
                null=True,
                verbose_name="Id на сессии",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_url",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=400,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
    ]
